---
title: 'ESM 244 HW1A: Space Launch Wrangling'
author: "Kynan Witters Hicks"
date: "January 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE}

library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(plyr)

```

```{r data}

agencies <- read.csv("agencies.csv")
launches <- read.csv("launches.csv")

```

```{r select data to analyze}

state_names <- levels(launches$state_code)

#BR - Brazil
#CN - China
#CYM - Cayman Islands
#F - France
#I - Israel
#I-ELDO - 
#I-ESA - 
#IL - Italy
#IN - India
#IR - Iran
#J - Japan
#KP - North Korea
#KR - South Korea
#RU - Russia
#SU - Soviet Union
#UK - United Kingdom
#US - United States


launch_time <- launches %>% 
  group_by(launch_year, state_code) %>% 
  tally() %>% 
  dplyr::rename(launches = n) %>% 
  dplyr::rename(state = state_code) %>% 
  mutate(name = case_when(
    grepl("J", state) ~ "Japan",
    grepl("US", state)~ "United State",
    grepl("BR", state)~ "Brazil",
    grepl("F", state)~ "France",
    grepl("CN", state)~ "China",
    grepl("I", state)~ "Israel",
    grepl("IL", state)~ "Italy",
    grepl("IR", state)~ "Iran",
    grepl("RU", state)~ "Russia",
    grepl("SU", state)~ "Soviet Union",
    grepl("UK", state)~ "United Kingdom",
    grepl("KP", state)~ "North Korea",
    grepl("KR", state)~ "South Korea",
    grepl("CYM", state)~ "Cayman Islands",
    grepl("I-ELDO", state)~ "Other",
    grepl("I-ESA", state)~ "Other")) 
  

launch_success <- launches %>% 
  select(launch_date, launch_year, agency, state_code, category) %>% 
  group_by(launch_year, state_code, category) %>% 
  tally() 

```

```{r visualize}

colors_man <- c("cadetblue2", 
                "chocolate2",
                "coral2",
                "aquamarine2",
                "darkgoldenrod2",
                "brown2",
                "darkorchid2",
                "darkseagreen2",
                "deeppink2",
                "coral2",
                "azure3",
                "cornsilk2")

names(colors_man) <- unique(launch_time$names)

gglaunch <- ggplot(launch_time, aes(x = launch_year, y = launches, fill = name)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values = colors_man) +
    theme_bw()

gglaunch



#need to figure out color pallete - scale_fill_brewer(palette = "Spectral") not have enough
#create own colors in 

#df_name <- c("colors", "color1"...)
#names(df_name) <- unique(launch_time$state)
#scale_fill_manual(values = df_name)

#substr - extract or replace strings in a character vector


```

